replicaCount: 1

image:
  repository: mits01/test
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hello-tls
      hosts:
        - hello.local
